# config.yaml

# === SERIAL PORT SETTINGS ===
serial:
  port: "COM5"
  baud_rate: 500000

# === AUDIO / SAMPLING SETTINGS ===
audio:
  sample_rate: 22050
  block_size: 512


# === WINDOW CALCULATED ===
window:
  size: 44100               # sample_rate * window_duration
  step: 22050               # sample_rate * step_duration

# === LOGGING SETTINGS ===
logging:
  log_dir: "Logs"
  rotation_minutes: 3

# === COMPONENT NAMES ===
components:
  - mast
  - elevator
  - gripper
  - shuttle
  - environment

# === MODEL PATHS ===
models:
  iso: "model_files/iso_model.joblib"
  log_reg: "model_files/log_reg_model.joblib"

testers:
  name: "IPC1"

batch:
  size: 30
  wav_dir: "wav_file_temp"

mfcc:
  n_mfcc: 13
  max_frames: 63
